### ISSUE TITLE
Doesn't work on macOS 11.1 with M1 chip

### ISSUE THREAD

**Issue by csuft** [bobbyg603/myQtCrasher#13]
I've compiled the project on my macbook pro with M1 chip. The compiling process is done without errors, but when the app crashed it just created three empty folders, no dump files generated. Does that mean the project doesn't support M1 chip yet?
<img width="292" alt="iShot2021-02-01 18 42 50" src="https://user-images.githubusercontent.com/3948137/106448146-53a74600-64bd-11eb-807c-41ae216521b4.png">

**Comment by bobbyg603** [comment]
@csuft If I had to guess this is likely because we haven't included the ARM64 Crashpad libraries in this project, we'll do that soon. 

In the meantime, you can rebuild Crashpad to target ARM64. Here's a handy [guide](https://www.bugsplat.com/docs/sdk/crashpad/building/) that shows how to build Crashpad. Here's a post on [Stack Overflow](https://stackoverflow.com/a/64768853/2993077) that describes how to set build arguments when using `gn gen`. You'll want to play around with the [target_cpu](https://gn.googlesource.com/gn/+/master/docs/reference.md#var_target_cpu) value and possibly other values in order to get something working.

If you get this working before we do, please comment on this issue with the steps you took to get Crashpad working on your M1 Mac 🙂.

**Comment by bobbyg603** [comment]
@csuft also, I found this [change](https://groups.google.com/a/chromium.org/g/crashpad-dev/c/1D7rHS7iOMw/m/_N_RecFMAQAJ), you might experiment with the "mac_universal" target_cpu value.

**Comment by csuft** [comment]
@bobbyg603 Thanks, I'll give it a try.

**Comment by bobbyg603** [comment]
@csuft try building and running from the `crashpad-update` branch. I've built Crashpad targeting mac_universal but unfortunately don't have access to an M1 machine to test the fix.

**Comment by csuft** [comment]
I compiled the branch but no window showed up. My Qt version is 5.14.0, and clang version is 10.0. This is curious because I have many other Qt projects which also compiled with this Qt version, but they are running normally.

**Comment by bobbyg603** [comment]
@csuft We ran into this as well, for some reason the project seemed to have rusted on us. We installed and used Qt 6 as the target which fixed the issue. Unfortunately we still weren't able to generate minidump files on an M1 Mac. Our next thought was to try targeting `arm64` instead of `mac_universal` but haven't gotten there yet.

**Comment by bobbyg603** [comment]
@csuft if you're still looking for qt crash reporting for the M1 Mac you can try [Bugsplat-Mac](https://github.com/BugSplat-Git/BugSplatMac) which does support M1 ARM Macs.

**Comment by vadi2** [comment]
Does that one work with Qt?

**Comment by bobbyg603** [comment]
@vadi2 we have at least 1 customer who has successfully integrated with Qt as far as I'm aware. Unfortunately we haven't had a chance to test it internally.

**Comment by bobbyg603** [comment]
@csuft @vadi2 i recently came across a post that mentioned Crashpad is not supported for apps running on Rosetta. Maybe there are build changes required to get Qt to output either a native M1 or mac universal binary?

**Comment by bobbyg603** [comment]
Sorry for the delay @csuft - this issue has been fixed by PR #21. Please let us know if we need to take another look. Hope this helps!
