### ISSUE TITLE
Can you provide more compiled library files for crashpad?

### ISSUE THREAD

**Issue by libaineu2004** [bobbyg603/myQtCrasher#22]
Can you provide more compiled library files for crashpad?
Windows x86
Windows x64
debug
release
MD
MT
etc...

**Comment by libaineu2004** [comment]
I know this site can download crashpad library for windows,
https://docs.bugsplat.com/introduction/getting-started/integrations/cross-platform/crashpad

But its version is too old and not updated in time.
Help me.

**Comment by bobbyg603** [comment]
Hi @libaineu2004 

Thus far we've found that no matter how we build Crashpad we get errors if the exact same version of Visual Studio is not used to build the Qt project so your best bet is to build Crashpad on your own system. Also, Qt projects don't seem to play nicely with /MT and /MTd and thus you'll want to go with /MD and /MDd.

Here's a [guide](https://docs.bugsplat.com/introduction/getting-started/integrations/cross-platform/crashpad/how-to-build-google-crashpad) for building Crashpad on your system. Here's a Stack Overflow [post](https://stackoverflow.com/a/64768853/2993077) that will help you modify your Crashpad build in order to build with the /MD or /MDd flag.

Hope this helps.

**Comment by libaineu2004** [comment]
Is the library of this address x64 /MD?
https://github.com/BugSplat-Git/my-qt-crasher/tree/master/Crashpad/Libraries/Windows

Could you please submit the lib files of /MDd? Otherwise, there is no way for debug to compile.

**Comment by bobbyg603** [comment]
@libaineu2004 I believe the libraries have been built with /MDd, what error are you experiencing?

**Comment by libaineu2004** [comment]
> @libaineu2004 I believe the libraries have been built with /MDd, what error are you experiencing?

fatal error C1900: Il mismatch between "P1" (version "20211014") and "P2" (version "20210202")
LINK : fatal error LNK1257: code generation failed

My development environment is, VS2019 x64/Qt 5.12.11

**Comment by bobbyg603** [comment]
> > @libaineu2004 I believe the libraries have been built with /MDd, what error are you experiencing?
> 
> fatal error C1900: Il mismatch between "P1" (version "20211014") and "P2" (version "20210202") LINK : fatal error LNK1257: code generation failed
> 
> My development environment is, VS2019 x64/Qt 5.12.11

@libaineu2004 I believe that error is due to a toolset mismatch (Visual Studio version that build Crashpad is different than version building Qt) which we have not found a solution for. Our workaround thus far has been to suggest users build Crashpad on their own systems, that way you can guarantee the version of Visual Studio that builds Crashpad is the same as the version that builds the Qt project. We will look into a better solution here in the future, but for now your best bet is to follow our guide and build Crashpad on your system.

**Comment by bobbyg603** [comment]
> > @libaineu2004 I believe the libraries have been built with /MDd, what error are you experiencing?
> 
> fatal error C1900: Il mismatch between "P1" (version "20211014") and "P2" (version "20210202") LINK : fatal error LNK1257: code generation failed
> 
> My development environment is, VS2019 x64/Qt 5.12.11

This Stack Overflow [post](https://stackoverflow.com/questions/8959973/il-mismatch-between-p1-version-20080116-and-p2-version-20070207) has an answer with a few solutions you might try as well. The suggestion about turning off /LTGC seems the most promising.

**Comment by bobbyg603** [comment]
After discussing with @daveplunkett we thought we might be able to build Crashpad in a way that's more widely compatible by turning off whole program optimization (/GL https://docs.microsoft.com/en-us/cpp/build/reference/gl-whole-program-optimization?view=msvc-170). I'm not sure we can do this easily with gn and ninja but we're going to try!

**Comment by libaineu2004** [comment]
> After discussing with @daveplunkett we thought we might be able to build Crashpad in a way that's more widely compatible by turning off whole program optimization (/GL https://docs.microsoft.com/en-us/cpp/build/reference/gl-whole-program-optimization?view=msvc-170). I'm not sure we can do this easily with gn and ninja but we're going to try!

OK. I wish you early success! Submit MD along with MDd's library by then! Thanks!

**Comment by bobbyg603** [comment]
> > After discussing with @daveplunkett we thought we might be able to build Crashpad in a way that's more widely compatible by turning off whole program optimization (/GL https://docs.microsoft.com/en-us/cpp/build/reference/gl-whole-program-optimization?view=msvc-170). I'm not sure we can do this easily with gn and ninja but we're going to try!
> 
> OK. I wish you early success! Submit MD along with MDd's library by then! Thanks!

@libaineu2004 I've opened a PR that addresses this, please see #26. I'm testing at the moment and hope to merge it soon (assuming the testing goes well).
